# Site settings
title: Edson Júnior
description: 'Um desenvolvedor fullstack, amante de novas tecnologias, jogos, filmes e séries. Tenta dar uma de guitarrista nas horas vagas.'
url: 'http://ebfjunior.github.io/'
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'
disqus_shortname: 'ebfjunior'

author:
  name: 'Edson Júnior'
  email: ejunior.batista@gmail.com
  twitter_username: ebfjunior
  # facebook_username: ebfjunior
  github_username:  ebfjunior
  linkedin_username:  ebfjunior

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']

collections:
  - series
